services:
  - type: web
    name: beyond-eta
    env: node
    region: oregon
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - path: /
        destination: /
